"""
generate_tests.py
-----------------
CLI runner — generates AI-powered FHIR Patient tests and writes them
to projects/healthcare_fhir/api/ai/generated/test_patient_ai.py.

Also runs the staleness detector against the hand-crafted Phase 1 tests
and prints a clean report.

Usage
-----
    # From repo root:
    export ANTHROPIC_API_KEY=your_key_here
    python generate_tests.py

    # Dry run — print generated code without saving:
    python generate_tests.py --dry-run

    # Staleness check only — no generation:
    python generate_tests.py --stale-check-only
"""

from __future__ import annotations

import argparse
import sys
from datetime import datetime
from pathlib import Path

REPO_ROOT     = Path(__file__).parent
OUTPUT_PATH   = REPO_ROOT / "projects/healthcare_fhir/api/ai/generated/test_patient_ai.py"
PHASE1_TESTS  = REPO_ROOT / "projects/healthcare_fhir/api/tests/test_patient.py"

sys.path.insert(0, str(REPO_ROOT))

from projects.healthcare_fhir.api.ai.fhir_spec_loader import FhirSpecLoader
from projects.healthcare_fhir.api.ai.fhir_test_generator import FhirTestGenerator
from projects.healthcare_fhir.api.ai.staleness_detector import StalenessDetector


# ------------------------------------------------------------------ #
#  Header injected at top of every generated file                     #
# ------------------------------------------------------------------ #

def _file_header() -> str:
    timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    return f'''"""
test_patient_ai.py
------------------
AUTO-GENERATED by generate_tests.py using Claude (Anthropic SDK).
Generated : {timestamp}

DO NOT EDIT MANUALLY — re-run generate_tests.py to regenerate.
Hand-crafted tests live in: tests/test_patient.py

Framework stack: FhirClient (Facade) · FhirValidator (Fluent) ·
                 FhirFactory (Factory) · pytest fixtures (conftest.py)
"""
'''


# ------------------------------------------------------------------ #
#  Main                                                                #
# ------------------------------------------------------------------ #

def main() -> None:
    parser = argparse.ArgumentParser(
        description="AI-powered FHIR test generator"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print generated code to stdout without saving",
    )
    parser.add_argument(
        "--stale-check-only",
        action="store_true",
        help="Run staleness detector only — skip generation",
    )
    args = parser.parse_args()

    # ── Staleness check ──────────────────────────────────────────── #
    print("\n── Staleness check ─────────────────────────────────────")
    detector = StalenessDetector()
    report   = detector.scan(PHASE1_TESTS)
    print(report.summary())

    if args.stale_check_only:
        sys.exit(1 if report.is_stale() else 0)

    # ── AI test generation ───────────────────────────────────────── #
    print("\n── AI test generation ──────────────────────────────────")
    print(f"Model  : claude-sonnet-4-6")
    print(f"Spec   : FHIR R4 Patient (minimal built-in spec)")
    print(f"Output : {OUTPUT_PATH.relative_to(REPO_ROOT)}")
    print()
    print("Calling Anthropic API...")

    loader    = FhirSpecLoader()
    spec      = loader.load_minimal_patient_spec()
    generator = FhirTestGenerator()

    try:
        generated_code = generator.generate(spec)
    except EnvironmentError as exc:
        print(f"\nERROR: {exc}")
        sys.exit(1)
    except Exception as exc:
        print(f"\nUnexpected error during generation: {exc}")
        sys.exit(1)

    full_output = _file_header() + "\n" + generated_code

    if args.dry_run:
        print("\n── Generated code (dry run) ────────────────────────────")
        print(full_output)
        print("\n── Dry run complete — nothing written to disk ──────────")
        return

    # Write to disk
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(full_output, encoding="utf-8")

    print(f"Done. Generated {len(generated_code.splitlines())} lines.")
    print(f"Saved to: {OUTPUT_PATH.relative_to(REPO_ROOT)}")
    print()
    print("Run the generated tests with:")
    print("  pytest projects/healthcare_fhir/api/ai/generated/ -v")


if __name__ == "__main__":
    main()
