[pytest]
testpaths = api
addopts =
    -v
    -n auto
    --alluredir=allure-results
    --clean-alluredir
markers =
    smoke: smoke tests
    regression: full regression suite
    petstore: petstore API tests